format = "$directory$git_branch$python$git_status\n$character"
add_newline = false

[directory]
truncation_length = 3

[git_branch]
symbol = " "

[python]
format = "[\\($virtualenv\\)]($style) "

[character]
success_symbol = "[\uf0a9](bold green) "
error_symbol = "[\uf0a9](bold red) "
